package Pastelyst::Model::PasteDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Pastelyst::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:/home/brad/Pastelyst/root/db/pastes.db',
        user => '',
        password => '',
    }
);

=head1 NAME

Pastelyst::Model::PasteDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Pastelyst>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Pastelyst::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

Brad Haywood

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
